org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.248
neo_version_range=[21.1,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.10
parchment_mappings_version=2025.10.12
mod_id=valescentbar
mod_name=ValescentBar
mod_license=All Rights Reserved
mod_version=1.1.0
mod_group_id=com.sammmy
mod_authors=sammmy
mod_description=Implement a custom hotbar underlay and/or overlay through resource packs.\n\nPrimarily made for Valescence: Renewal
